openapi: 3.0.1
info:
  title: Presentation Plugin
  description: A plugin that allows the user to create slides using ChatGPT. It allows you to say different things and it will return the right slides back.
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /presentation:
    post:
      operationId: addPresentation
      summary: Create a presentation from a JSON array. Pass in a list of object in a json array with a heading (string), body (string) and layout (int) in each object
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/addPresentationRequest'
      responses:
        "200":
          description: OK
components:
  schemas:
    addPresentationRequest:
      type: object
      required:
      - slide_data
      properties:
        slide_data:
          type: array
          description: You need to pass in an object with slide_data then an array of objects in a json array with a heading (string), body (string) and layout (int) in each object
          items:
            type: object
